### ISSUE TITLE
arbitrary content inside <CircularProgressbarWithChildren> is missplaced when direction is rtl

### ISSUE THREAD

**Issue by codewithanujith** [kevinsqi/react-circular-progressbar#125] opened 2019-11-11 07:04 UTC
### Summary of issue

The children inside the <CircularProgressbarWithChildren> </CircularProgressbarWithChildren> component is getting positioned on top of the progress bar instead of in the center when direction rtl is applied to any parent container.

### Reproducible example

https://codesandbox.io/s/react-circular-progressbar-issue-template-h86x2

### Your environment

Chrome Version 78.0.3904.97 (Official Build) (64-bit) for macOS

**Comment by kevinsqi** [comment] 2019-11-15 22:44
Interesting issue, thanks for reporting! I'll look into it.

**Comment by kevinsqi** [comment] 2020-02-05 00:11
Sorry for the delay in looking at this! I saw the issue back in November, but as of now it appears that the issue no longer occurs?

![Screen Shot 2020-02-04 at 4 09 46 PM](https://user-images.githubusercontent.com/396006/73798781-c970b880-4768-11ea-884a-ed80f38d1eef.png)

Let me know if the issue is now fixed for you, too.

**Closed** 2020-04-08 04:37 UTC
